apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      selector:
    matchLabels:
      app: frontend-service 
    spec:
      containers:
      - name: frontend
        image: gcr.io/tutorial-282518/frontend:latest
        ports:
        - containerPort: 8080
          protocol: TCP

            
