apiVersion: v1
kind: deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/tutorial-282518/frontend:latest
        ports:
        - containerPort: 50001
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m



