apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: frontend
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 5000
    