apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  metadata:
      labels:
        io.kompose.service: frontend
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50001
    