apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - host: hostname
    http:
      paths:
      - backend:
          serviceName: frontend-deployment
          servicePort: 8080
        path: /(.*)
