apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: frontend-deployment
  type: NodePort
